# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-a1bae383-7470-4de8-8d80-0b42cb8d18c2";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-a1bae383-7470-4de8-8d80-0b42cb8d18c2".device =
    "/dev/disk/by-uuid/a1bae383-7470-4de8-8d80-0b42cb8d18c2";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D82D-0EDF";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
