# Oxocarbon Dark - Kitty
# Author: shaunsingh/IBM

background #161616
foreground #f2f4f8
cursor #08bdba

# black
color0 #161616
color8 #262626

# red
color1 #3ddbd9
color9 #78a9ff

# green
color2 #ee5396
color10 #33b1ff

# yellow
color3 #ff7eb6
color11 #42be65

# blue
color4 #be95ff
color12 #82cfff

# magenta
color5 #525252
color13 #dde1e6

# cyan
color6 #ffffff
color14 #08bdba

# white
color7 #f2f4f8
color15 #ffffff