# font_family      MonaspiceNe Nerd Font Mono
# bold_font        MonaspiceNe Nerd Font Mono
# italic_font      MonaspiceNe Nerd Font Mono
# bold_italic_font MonaspiceNe Nerd Font Mono

font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font
italic_font      JetBrainsMono Nerd Font
bold_italic_font JetBrainsMono Nerd Font

font_size                       18
font_features                   CartographCF-Regular +ss02
modify_font                     underline_thickness 1
modify_font                     underline_position 18
modify_font                     strikethrough_position -3px

macos_option_as_alt left

window_margin_width 0
window_padding_width 5
hide_window_decorations titlebar-only

tab_bar_edge top
tab_bar_margin_width 5.0
tab_bar_margin_height 30.0 3.0

tab_bar_style powerline

tab_title_template "{index} {tab.active_wd.replace('/Users/xxxxxxx', '~')}{' :{}:'.format(num_windows) if num_windows > 1 else ''}"

background_opacity 0.97

macos_show_window_title_in none


include kitty-github-dimmed.conf
cursor none
