# font_family      MonaspiceNe Nerd Font Mono
# bold_font        MonaspiceNe Nerd Font Mono
# italic_font      MonaspiceNe Nerd Font Mono
# bold_italic_font MonaspiceNe Nerd Font Mono

font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font
italic_font      JetBrainsMono Nerd Font
bold_italic_font JetBrainsMono Nerd Font

font_size                       18
font_features                   CartographCF-Regular +ss02
modify_font                     underline_thickness 1
modify_font                     underline_position 18
modify_font                     strikethrough_position -3px

# Misc
scrollback_lines 10000
touch_scroll_multiplier 2.0
copy_on_select yes
enable_audio_bell no
remember_window_size  yes
initial_window_width  1600
initial_window_height 1000
enabled_layouts Splits,Stack
tab_bar_style powerline
tab_separator " "
dynamic_background_opacity yes
scrollback_pager ~/.local/share/bob/nvim-bin/nvim -c "lua require('util').colorize()"

tab_title_template "{title}{fmt.bold}{'  ' if num_windows > 1 and layout_name == 'stack' else ''}"

kitty_mod cmd+shift
map kitty_mod+l next_tab
map kitty_mod+h previous_tab
map kitty_mod+m toggle_layout stack
map kitty_mod+z toggle_layout stack
map kitty_mod+enter launch --location=split --cwd=current
map kitty_mod+\ launch --location=vsplit    --cwd=current
map kitty_mod+minus launch --location=hsplit --cwd=currentt
map kitty_mod+left neighboring_window left
map kitty_mod+right neighboring_window right
map kitty_mod+up neighboring_window up
map kitty_mod+down neighboring_window down
map kitty_mod+r show_scrollback
map ctrl+space send_text all \x00


include kitty-oxcocarbon16.conf
cursor none
